name: github pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.34'
          # mdbook-version: 'latest'

      - run: mdbook build docs

      - name: Upload documentation to github pages
        if: matrix.os == 'ubuntu-18.04'
        uses: crazy-max/ghaction-github-pages@v1.4.0
        with:
          build_dir: docs/book
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
